---
title:
output: 
  html_document:
    includes:
      after_body: footer.html
---


<p>&nbsp;</p>

### **Research [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=9AqXyqQAAAAJ&hl=it&oi=sra){target="_blank"} [ <i class="ai ai-ideas-repec"></i>](https://ideas.repec.org/f/pva895.html){target="_blank"} **



##### ***-  Work in Progress***


* [Monetization, wars, and the Italian fiscal multiplier](http://docs.dises.univpm.it/web/quaderni/pdfmofir/Mofir176.pdf){target="_blank"} (with M. Fratianni, F. Giri and R. Lucchetti) 


* [Persistence of R&D intensities in the world’s top investors in R&D](http://docs.dises.univpm.it/web/quaderni/pdf/480.pdf){target="_blank"} (with C. Pigini and A. Sterlacchini)


* [Specification testing with Grouped Fixed Effects](http://arxiv.org/pdf/2310.01950){target="_blank"} (with C. Pigini and A. Pionati)


* Testing for dependence in pairs of binary outcomes by an approximating logit model

<p>&nbsp;</p>

##### ***-  Peer-Reviewed Articles***   </span>

* [<ins>MCMC Conditional Maximum Likelihood for the two-way fixed-effects logit</ins>](https://doi.org/10.1080/07474938.2024.2339145){target="_blank"}
  
  ***Econometric Reviews***, 2024, with F. Bartolucci and C. Pigini [<i class="fa fa-github"></i>Code](https://github.com/fravale/mcmc_cml_replication){target="_blank"}
<p>&nbsp;</p>


*  [<ins>Linear models with time-varying parameters: a comparison of different approaches</ins>](https://link.springer.com/article/10.1007/s00180-023-01452-3){target="_blank"}
  
    ***Computational Statistics***,     2024, with R. Lucchetti [<i class="fa fa-github"></i>Code](https://github.com/fravale/replication_tvp_gretl){target="_blank"} 
<p>&nbsp;</p>





* [<ins>Kernel-based Time-Varying IV estimation: handle with care</ins>](https://link.springer.com/article/10.1007/s00181-023-02450-6){target="_blank"}
  
  ***Empirical Economics***, 2023, with R. Lucchetti [<i class="fa fa-github"></i>Code](https://github.com/fravale/replication_gkm){target="_blank"} 
<p>&nbsp;</p>


* [<ins>Testing for state dependence in the fixed-effects ordered logit model</ins>](https://doi.org/10.1016/j.econlet.2022.110964){target="_blank"}

  ***Economics Letters***, 2022, with F. Bartolucci and C. Pigini
<p>&nbsp;</p>

* [<ins>Conditional inference and bias reduction for partial effects estimation of fixed-effects logit models</ins>](https://doi.org/10.1007/s00181-022-02313-6){target="_blank"}

  ***Empirical Economics***, 2022, with F. Bartolucci and C. Pigini [<i class="fa fa-github"></i>Code](https://github.com/fravale/replication_ape_logit){target="_blank"} 
<p>&nbsp;</p>

* [<ins>Recursive computation of the conditional probability function of the quadratic exponential model for binary panel data</ins>](https://doi.org/10.1007/s10614-021-10218-2){target="_blank"}

  ***Computational Economics***, 2021, with F. Bartolucci and C. Pigini    
<p>&nbsp;</p>


* [<ins>Do Covid-19 mobility restrictions affect economic uncertainty in Italy? Evidence from a SVAR approach</ins>](http://www.accessecon.com/pubs/eb/default.aspx?topic=Abstract&PaperID=EB-21-00637){target="_blank"}

  ***Economics Bulletin***, 2021, with C. Casoli and L. Pedini [Download](http://www.accessecon.com/Pubs/EB/2021/Volume41/EB-21-V41-I4-P209.pdf){target="_blank"}

<p>&nbsp;</p>

##### ***-  Books***
* [<ins>Advances in maximum likelihood estimation of fixed-effects binary panel data models</ins>](https://link.springer.com/chapter/10.1007/978-3-031-31186-4_9){target="_blank"}

  in ***Trends and Challenges in Categorical Data Analysis***, Springer, 2023, with F. Bartolucci and C. Pigini [<i class="fa fa-github"></i>Code](https://github.com/fravale/replication_fe_dyn_logit){target="_blank"}

<p>&nbsp;</p>


<p>&nbsp;</p>

### **Software**


* [**cquad**](https://cran.r-project.org/web/packages/cquad/index.html){target="_blank"}: Conditional Maximum Likelihood for Quadratic Exponential Models for Binary Panel Data. [R](https://www.r-project.org/){target="_blank"} package.

* [**cquadr**](https://ideas.repec.org/c/boc/bocode/s458852.html){target="_blank"}: Stata module to estimate Quadratic Exponential models running the cquad R package. [Stata](https://www.stata.com/){target="_blank"} module. [User's Guide](https://github.com/fravale/cquadr/blob/master/cquadr-guide.pdf){target="_blank"} and [code](https://github.com/fravale/cquadr){target="_blank"} are also available in my GitHub repository.

* [**FLS**](https://gretl.sourceforge.net/current_fnfiles/FLS.zip): Flexible Least Squares.
[gretl](http://gretl.sourceforge.net/){target="_blank"} function package. [Documentation](https://gretl.sourceforge.net/current_fnfiles/unzipped/FLS.pdf) is available.  

* [**ketvals**](http://gretl.sourceforge.net/current_fnfiles/ketvals.zip): Kernel-based Time-Varying Least Squares. [gretl](http://gretl.sourceforge.net/){target="_blank"} function package. [Documentation](http://gretl.sourceforge.net/current_fnfiles/unzipped/ketvals.pdf){target="_blank"} is available.

* [**spm**](http://gretl.sourceforge.net/current_fnfiles/spm.zip): Spatial Regression Models. [gretl](http://gretl.sourceforge.net/){target="_blank"} function package. A related [article](http://www.fedoa.unina.it/12338/1/GRETL2019.pdf#page=33){target="_blank"} and [documentation](http://gretl.sourceforge.net/current_fnfiles/unzipped/spm.pdf){target="_blank"} are available.
